[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "Terbium"
versionNumber = "0.0.4"
description = "Improves load times by stopping configs saving too many times!"
websiteUrl = "https://github.com/LoafOrc/Terbium"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./Thunderstore/icon.png"
readme = "./Thunderstore/README.md"
outdir = "./build"

[[build.copy]]
source = "./TerbiumPreloader/bin/Release/netstandard2.1/me.loaforc.terbium.preloader.dll"
target = "./BepInEx/patchers/me.loaforc.terbium.preloader.dll"


[publish]
repository = "https://thunderstore.io"
communities = [ "riskofrain2", ]
[publish.categories]
riskofrain2 = [ "items", "skills", ]


